### ISSUE TITLE
Function WP_Block_Type_Registry::unregister was called incorrectly

### ISSUE THREAD

**Issue by huubl** [happyprime/turn-comments-off#6]
Hi,

I get a warning:

`Function WP_Block_Type_Registry::unregister was called <strong>incorrectly</strong>. Block type "core/comments-query-loop" is not registered. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.)`

https://github.com/happyprime/turn-comments-off/blob/41387465da40b079f85565778bd37fb005d91672/plugin.php#L112-L129

**Comment by jeremyfelt** [comment]
Thanks @huubl. I used most of your approach from #7, but then switched the action back to `init` so that the blocks are unregistered everywhere and not just in the editor. I appreciate the issue and the pull request!
